app:
  build: ./hackathon-app
  volumes:
    - /var/log/hackathon/nginx:/var/log/nginx
    - /var/log/hackathon/php-fpm:/var/log/php5-fpm
    - /var/www/project:/var/www/project
  environment:
    TOPFACE_USER: whatever
    PLATFORM: dev
  ports:
    - "80:80"
    - "443:443"
  links:
    - redis
    - redisUser
    - redisEvent
    - redisStatistics
    - redisOther
    - mc
    - mysql
redis:
  image: redis:2.8
  volumes:
    - /var/db/redis:/data
redisUser:
  image: redis:2.8
  volumes:
    - /var/db/redisUser:/data
redisEvent:
  image: redis:2.8
  volumes:
    - /var/db/redisEvent:/data
redisStatistics:
  image: redis:2.8
  volumes:
    - /var/db/redisStatistics:/data
redisOther:
  image: redis:2.8
  volumes:
    - /var/db/redisOther:/data
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysqlsecretrootpassord
    MYSQL_USER: hackathon
    MYSQL_PASSWORD: hackathonpassword
    MYSQL_DATABASE: hackathon
  volumes:
    - /var/db/mysql:/var/lib/mysql
mc:
  image: memcached:latest
  command: memcached -m 512
