app:
  build: ./hackathon-app
  volumes:
    - /var/log/hackathon/nginx:/var/log/nginx
    - /var/log/hackathon/php-fpm:/var/log/php5-fpm
    - /var/www/project:/var/www/project
  environment:
    TOPFACE_USER: whatever
    PLATFORM: dev
  ports:
    - 80:80
    - 443:443
  links:
    - redis
    - stat
    - mc
    - mysql
redis:
  image: redis:2.8
  volumes:
    - /var/db/redis:/data
stat:
  build: ./hackathon-stat
  ports:
    - 13200:13200
  links:
    - mysql
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysqlsecretrootpassord
    MYSQL_USER: hackathon
    MYSQL_PASSWORD: hackathonpassword
    MYSQL_DATABASE: hackathon
  volumes:
    - /var/db/mysql:/var/lib/mysql
mc:
  image: memcached:latest
  command: memcached -m 512
