app:
  build: ./hackathon-app
  volumes:
    - /Users/pavlik/Projects/photo-contest/log/nginx:/var/log/nginx
    - /Users/pavlik/Projects/photo-contest/log/php-fpm:/var/log/php5-fpm
    - /Users/pavlik/Projects/hackathon-photo-contest:/var/www/project
  environment:
    TOPFACE_USER: pavlik
    PLATFORM: dev
  ports:
    - "80:80"
    - "443:443"
  links:
    - redis:hackathon_redis_1
    - redisUser:hackathon_redisUser_1
    - redisEvent:hackathon_redisEvent_1
    - redisStatistics:hackathon_redisStatisitcs_1
    - redisOther:hackathon_redisOther_1
    - mc:hackathon_mc_1
    - mysql:hackathon_mysql_1
redis:
  image: redis:2.8
redisUser:
  image: redis:2.8
redisEvent:
  image: redis:2.8
redisStatistics:
  image: redis:2.8
redisOther:
  image: redis:2.8
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysqlsecretrootpassord
    MYSQL_USER: hackathon
    MYSQL_PASSWORD: hackathonpassword
    MYSQL_DATABASE: hackathon
mc:
  image: memcached:latest
  command: memcached -m 512
