app:
  build: ./hackathon-app
  volumes:
    - /var/log/hackathon/nginx:/var/log/nginx
    - /var/log/hackathon/php-fpm:/var/log/php5-fpm
    - /var/www/project:/var/www/project
  environment:
    TOPFACE_USER: whatever
    PLATFORM: dev
  ports:
    - "80:80"
    - "443:443"
  links:
    - redis
    - redisUser
    - redisOther
    - pg
    - mc
    - mysql
redis:
  image: redis:2.8
  volumes:
    - /var/db/redis:/data
redisUser:
  image: redis:2.8
  volumes:
    - /var/db/redisUser:/data
redisOther:
  image: redis:2.8
  volumes:
    - /var/db/redisOther:/data
pg:
  image: sameersbn/postgresql:9.4
  volumes:
    - /var/db/postgresql/:/var/lib/postgresql/
  environment:
    DB_USER: hackathon
    DB_PASS: sosecretpassword
    DB_NAME: hackathon
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysqlsecretrootpassord
    MYSQL_USER: hackathon
    MYSQL_PASSWORD: hackathonpassword
    MYSQL_DATABASE: hackathon
  volumes:
    - /var/db/mysql:/var/lib/mysql
mc:
  image: memcached:latest
  command: memcached -m 512
